import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Welcome to the User Validation Form Powered by Java, Spring Boot,
            JWT, and Next.js
          </p>
        </div>

        <div className={styles.center}>
          <Link href={"/login"}>
            <Image
              className={styles.logo}
              src="/sp.png"
              alt="java.js Logo"
              width={80}
              height={80}
              priority
            />
          </Link>
        </div>

        <div>
          <a href="" target="_blank" rel="noopener noreferrer">
            By Ariel Ferencak
          </a>
        </div>
      </main>
    </>
  );
}
